CREATE TABLE EVENTS_ALL (
  ID                  BIGINT PRIMARY KEY AUTO_INCREMENT,
  FK_USER_ID          BIGINT NOT NULL,
  FK_EVENT_ID         BIGINT NOT NULL,
  FK_EVENT_STATUS_ID  BIGINT NOT NULL,
    CONSTRAINT FK_ALL_TO_USERS FOREIGN KEY (FK_USER_ID)
      REFERENCES USERS(ID),
    CONSTRAINT FK_ALL_TO_EVENTS FOREIGN KEY (FK_EVENT_ID)
      REFERENCES EVENTS (ID),
    CONSTRAINT FK_ALL_TO_EVENT_STATUS FOREIGN KEY (FK_EVENT_STATUS_ID)
      REFERENCES EVENT_STATUS (ID)
);

