CREATE TABLE USERS_TO_EVENTS (
  ID                BIGINT PRIMARY KEY AUTO_INCREMENT,
  FK_USER_ID        BIGINT NOT NULL,
  FK_EVENT_ID       BIGINT NOT NULL,
    CONSTRAINT FK_UTR_TO_USERS FOREIGN KEY (FK_USER_ID)
      REFERENCES USERS(ID),
    CONSTRAINT FK_UTR_TO_EVENTS FOREIGN KEY (FK_EVENT_ID)
      REFERENCES EVENTS (ID)
);